### ISSUE TITLE
R source incomplete

### ISSUE THREAD

**Issue by danascape** [OnePlusOSS/android_kernel_oneplus_sm6350#4]
Hey @op-codes , I'm thankful that you guys release R kernel source for OnePlus Nord N10 but after trying to build, it seems that the source code is incomplete.

For example :- External drivers included in techpack are missing and OnePlus drivers (which are inside drivers/OnePlus) are also missing
The build errors point out about the missing directories confirming that the source is missing something.

I request if you can look into it.
Expecting a quick response
Thank you

**Comment by kronflux** [comment]
@OnePlusOSS @OnePlusOSSAdmin @op-codes
Please do a complete kernel sources re-sync for branch SM6350_R_11.0
The sources are missing various components and cannot be built.

**Comment by kronflux** [comment]
@OnePlusOSS @OnePlusOSSAdmin @op-codes
We're still hoping for an update here, especially considering there have been multiple security patch releases since the initial sync of the R branch, and we still have an incomplete repository. Please re-sync the entire R branch, and include the oneplus drivers as needed to build the kernel.

**Comment by akaessens** [comment]
Still incomplete at 5d6f9d3869db19fdfc771a2eb9fc92edbb9d808a with `drivers/oneplus` missing

**Comment by danascape** [comment]
> Still incomplete at [5d6f9d3](https://github.com/OnePlusOSS/android_kernel_oneplus_sm6350/commit/5d6f9d3869db19fdfc771a2eb9fc92edbb9d808a) with `drivers/oneplus` missing

Don't worry, I have fixed the source and it boots and runs fine

**Comment by danascape** [comment]
https://github.com/danascape/kernel_oneplus_billie here

**Comment by kronflux** [comment]
Despite a sync, the kernel is STILL missing various components (specifically the drivers/oneplus directory) making this kernel completely useless and unable to be compiled in it's current state. A full RE-sync is required to include the missing components.

**Comment by SajiiCe** [comment]
You Can find this "OnePlus/Drivers" file in the other branch ( android_kernel_oneplus_sm6350-oneplus-SM6350_Q_10.0)

**Comment by lumiini** [comment]
Yes but that is for OxygenOS 10 not 11
